### ISSUE TITLE
elmine error handling

### ISSUE THREAD

**Issue by leoc** [kametoku/orgmine#11]
Hey there, just stumbled over your package using elmine. What would you expect elmine to do to clean up your code? Would love to help.

I have been using https://github.com/leoc/org-redmine.rb as a one-way sync (for now), but my ultimate goal is to have a tool that syncs new issues automatically into the respective org structure. Have you been working on something like that? Maybe we could combine efforts :-)

Cheers :beers:

**Comment by webframp** [comment]
Hey, I am also super interested to have stumbled on this question myself. I have been looking for something similar, a two way sync between org mode and redmine issues. I first found elmine, then this. 

Previously I only knew of this seemingly outdated project: https://github.com/gongo/org-redmine

**Comment by leoc** [comment]
@webframp Nice, I have added some more info to the README https://github.com/leoc/org-redmine.rb 

My ultimate goal is it to have a tool that automatically fetches all issues assigned to you and synchronizes it into an opinionated org-mode file structure. I do not want to manually fetch issues. I want to have a mirror of open issues in my org-files at any time. :-) We could discuss this further in the org-redmine.rb repo in leoc/org-redmine.rb#2

**Comment by kametoku** [comment]
Hi @leoc, nice to hear from you. :-)

I believe that orgmine already supports bidirectional synchronization between org file and redmine.

About ermine, at the very initial versions of orgmine, I adopted elmine as the redmine rest api backend for small start (great appreciation for the wonderful package). But I've been migrating the backend to use request.el package because it runs on curl command with powerful features. In the future (if I have time), I would like to make the sync run asynchronously.

**Comment by kametoku** [comment]
Let me close the issue since it remains open for a long time and there was no update.
